geertmeersman/aiorobonect

aiorobonect/client.py
=> async_cmds changed to dict

aiorobonect/client.py
=> Exceptions management

aiorobonect/client.py
=> Session closure

aiorobonect/client.py
=> JSON validator

aiorobonect/client.py
=> JSON UTF-8 encoding forced

aiorobonect/client.py
=> aiohttp response to utf-8

aiorobonect/client.py
=> fix: iso-8859-1 encoding for json answers

.github/scripts/pr_extract_labels.py, .github/workflows/pr-checker.yml, .pre-commit-config.yaml
=> PR Checker

.github/labels.yml, .github/scripts/pr_extract_labels.py, .github/workflows/pr-checker.yml, COMMIT_MESSAGES
=> feat: pr checker

aiorobonect/client.py
Robonect is available in:
- German
- French
- Italian
- English
- Swedish
ISO-8859-1 is missing some french characters,
ISO-8859-15 includes all of them and the €-symbol aswell.
=> Use ISO-8859-15 as it fully includes French and other language compatibility

aiorobonect/client.py
=> fix: Improved Robonect Exception

aiorobonect/client.py
=> fix: JSONDecodeError catching

aiorobonect/client.py
=> fix: response text (encoding=iso-8859-15)

.github/scripts/get_new_version.py, aiorobonect/client.py
=> fix: isinstance

aiorobonect/client.py
=> fix: don't update when parked

aiorobonect/client.py
=> fix: synctime => datetime.now()

README.md, aiorobonect/client.py
=> fix: replace aiohttp by httpx

aiorobonect/client.py
=> fix: take https scheme into account

aiorobonect/client.py
=> fix: only switch to https scheme on a redirect (3xx) or connection error

.github/FUNDING.yml, .github/scripts/get_new_version.py, .github/scripts/pr_extract_labels.py, .pre-commit-config.yaml, aiorobonect/__init__.py, aiorobonect/client.py, setup.py
=> fix: change logger error message to warning on requesterror

aiorobonect/client.py
=> fix: throw requesterror when response is none

aiorobonect/client.py
=> refactor: remove warning on requesterror, set it to debug

README.md
=> docs: example script update

aiorobonect/client.py
=> fix: catch incorrect robonect json

aiorobonect/client.py
The changes introduce a modification to the async_cmd method in the aiorobonect/client.py file. A conditional check is added to handle the "direct" command, ensuring the mower is stopped before executing further actions. If stopping the mower fails and the error code is not 7, a warning is logged, and execution returns early. Additionally, the client start operation is now initiated after this conditional check, maintaining the overall method structure while enhancing control flow.
=> feat: ensure mower stopped when calling direct mode
